### PR TITLE
fix: properly restore multi-select options when filtering

### LINKED ISSUE #260: multiple selection not restored correctly after search
In the Stackblitz of this repo, precisely in mat-select multiple with toggle selection; here is the steps to reproduce it:
1. Open multiselector with toggle,
2. Click checkbox toggle all (select all)
3. Click Checkbox toggle again (unselect all)
4.  Make some search in mat-select, and click one of them
5. The previous selection is selected, this is a error because previous we unselect all by toggle selection.

PD: this issue is not present in `3.0.0`

_Originally posted by @begandroide in https://github.com/bithost-gmbh/ngx-mat-select-search/issues/249#issuecomment-686068471_

A gif of the issue:

ezgif com-video-to-gif (1)

### PR DESCRIPTION
**Pull request by macjohnny**
fixes #260

### CODE REVIEW

File: src/app/mat-select-search/mat-select-search.component.ts [hunk 1]
```diff
@@ -641,16 +640,14 @@ export class MatSelectSearchComponent implements OnInit, OnDestroy, ControlValue
    *  Initialize this.previousSelectedValues whenever the selection changes and the search is empty
```
Comment (macjohnny) [inline src/app/mat-select-search/mat-select-search.component.ts:640]:
```suggestion
   *  Initialize this.previousSelectedValues whenever the search value changes and the previous search value was empty (i.e. the unfiltered selected options)
```
