### PR TITLE
#119 - Issue with scrollTop and keyboard selection

### LINKED ISSUE #119: [BUG] When using down or up arrow, the mat-select scrollTop isn't calculated correctly
Thanks for this component! 

I realize this might not be possible to fix without a dirty hack like I provided in the "Additionnal Context" section, but I thought maybe you'd be able to give a better approach.

**Describe the bug**
It looks like the height of the ngx-filter and the fact that it is above the other mat-options makes it so the mat-select can't calculate correctly where the scrolltop of its panel should be. 

When using the component inside a mat-option, the issue is when going "up" with the up arrow.
When using the component outside of a mat-option, the issue is when going "down" with the down arrow.

**To Reproduce**
1. Go to the demo https://stackblitz.com/github/bithost-gmbh/ngx-mat-select-search-example?file=src%2Fapp%2Fapp.component.html
2. Open the single selection example
3. Go to the bottom of the list using the down arrow
4. Go back to the top of the list with the up arrow
5. You should see that once the scroll bar starts going up, the active item is not visible, and that the first option is not visible. (It requires a manual scroll up)

The same can be observed with the component outside of a mat-option, but it's the other way around.

**Expected behavior**
When navigating up or down, the active item should correctly be displayed in the mat-select panel.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version Latest

**Additional context**
I was able to "fix" the issue by overriding private methods of MatSelect, but I would rather stay away from this:
```
this.matSelectElement['_scrollActiveOptionIntoView'] = (): void => {
            let activeOptionIndex = this.matSelectElement['_keyManager'].activeItemIndex || 0;
            let labelCount = _countGroupLabelsBeforeOption(activeOptionIndex, this.matSelectElement.options, this.matSelectElement.optionGroups);

            this.matSelectElement.panel.nativeElement.scrollTop = _getOptionScrollPosition(activeOptionIndex + labelCount,
                this.matSelectElement['_getItemHeight'](),
                this.matSelectElement.panel.nativeElement.scrollTop,
                SELECT_PANEL_MAX_HEIGHT - 51
            );
        };
```

It's the same implementation, but the height of the filter is substracted from "max height". I tested it with my ngx-search outside of the mat-option, but not inside. So it might not work for both.. maybe its +51 in that case? not sure..

### PR DESCRIPTION
**Pull request by Mabiro**
-Attempt at fixing the issue with _scrollActiveOptionIntoView when us…ing the ngx-mat-select-search input

Fixes #119 

I still had to import  _countGroupLabelsBeforeOption, sadly, to make it work with groups.

### CODE REVIEW

**Comment by Mabiro** [comment]
Any alternative to using _getItemHeight?

File: src/app/mat-select-search/mat-select-search.component.ts [hunk 1]
```diff
@@ -285,6 +285,30 @@ export class MatSelectSearchComponent implements OnInit, OnDestroy, AfterViewIni
             this.changeDetectorRef.markForCheck();
           });
       });
+
+      if (this.matSelect._keyManager) {
```
Comment (Mabiro) [inline src/app/mat-select-search/mat-select-search.component.ts]: Unfortunately, it looks like at this point, _keyManager was sometimes undefined. (It was the case for the app-custom-clear-icon-example component)

Is there a safer place I could subscribe to the event, where I can know for sure that _keyManager is defined?

**Comment by macjohnny** [comment]
@Mabiro thanks for your contribution. I will soon have a closer look

File: src/app/mat-select-search/mat-select-search.component.ts (hunk 1 above)
Comment (macjohnny) [reply src/app/mat-select-search/mat-select-search.component.ts]: it is initialized in the `ngAfterContentInit` lifecycle hook:
https://github.com/angular/material2/blob/eb5eed14778f402ea56a096148ff6e78d8bdad93/src/lib/select/select.ts#L542-L543

Comment (macjohnny) [inline src/app/mat-select-search/mat-select-search.component.ts]: could you move your implementation into a separate function? just to make it easier to read...

Comment (macjohnny) [reply src/app/mat-select-search/mat-select-search.component.ts]: so we need to try to initialize it in the `ngAfterViewInit()` and in the `ngAfterContentInit` lifecycle hook

Comment (macjohnny) [reply src/app/mat-select-search/mat-select-search.component.ts]: we should initialize first time after the mat select is opened (See https://github.com/bithost-gmbh/ngx-mat-select-search/pull/54):
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/4b92230643c50a777be5128b1fea014e9abace43/src/app/mat-select-search/mat-select-search.component.ts#L226-L232
however, i would keep the `if (this.matSelect._keyManager) {` and maybe add a console.log() to avoid errors if in some circumstances the keymanager is not initialized yet. See e.g. https://github.com/bithost-gmbh/ngx-mat-select-search/issues/53

Comment (Mabiro) [reply src/app/mat-select-search/mat-select-search.component.ts]: Done, sorry about that!

Comment (Mabiro) [reply src/app/mat-select-search/mat-select-search.component.ts]: I moved the subscribtion and added the console.log. 

However, I added a placeholder message for now, let me know what you think it should include.

**Comment by Mabiro** [comment]
@macjohnny : I am still having the _getItemHeight being a private method issue.

I could use ['_getItemHeight'](), but I am not sure I should.

**Comment by macjohnny** [comment]
> @macjohnny : I am still having the _getItemHeight being a private method issue.
> 
> I could use `['_getItemHeight']()`, but I am not sure I should.

wouldn't it be possible to get the height calculated in the dom with `getBoundingClientRect()` ?

**Comment by Mabiro** [comment]
> > @macjohnny : I am still having the _getItemHeight being a private method issue.
> > I could use `['_getItemHeight']()`, but I am not sure I should.
> 
> wouldn't it be possible to get the height calculated in the dom with `getBoundingClientRect()` ?

I'll give it a shot soon-ish!

**Comment by Mabiro** [comment]
@macjohnny  I added adjustScrollTopToFitActiveOptionIntoView on options change :)
