### PR TITLE
fix compare firstOptionIsChanged - use MatOption value

### LINKED ISSUE #445: [BUG] select search should compare values of options
https://github.com/bithost-gmbh/ngx-mat-select-search/blob/d2f18e8af0fb199374cbf52a85bb4e562c2d3bf8/src/app/mat-select-search/mat-select-search.component.ts#L351

compares the actual `MatOption` elements instead of their values

the `compareWith` operates on the values of the options. see https://material.angular.io/components/select/api

image

### PR DESCRIPTION
**Pull request by lorenzbaier**
closes #445

### CODE REVIEW

File: src/app/mat-select-search/mat-select-search.component.ts [hunk 1]
```diff
@@ -337,24 +337,24 @@ export class MatSelectSearchComponent implements OnInit, OnDestroy, ControlValue
...
 
               const keyManager = this.matSelect._keyManager;
-              if (keyManager && this.matSelect.panelOpen) {
+              if (keyManager && this.matSelect.panelOpen && currentFirstOption) {
 
                 // set first item active and input width
 
                 // Check to see if the first option in these changes is different from the previous.
-                const firstOptionIsChanged = !this.matSelect.compareWith(previousFirstOption, currentFirstOption);
+                const firstOptionIsChanged = !this.matSelect.compareWith(previousFirstOption.value, currentFirstOption.value);
```
Comment (macjohnny) [inline src/app/mat-select-search/mat-select-search.component.ts:351]:
```suggestion
                const firstOptionIsChanged = !previousFirstOption || !this.matSelect.compareWith(previousFirstOption.value, currentFirstOption.value);
```

File: src/app/mat-select-search/mat-select-search.component.ts [hunk 2]
```diff
@@ -337,24 +337,24 @@ export class MatSelectSearchComponent implements OnInit, OnDestroy, ControlValue
             // avoid "expression has been changed" error
             setTimeout(() => {
               // Convert the QueryList to an array
-              const options = this._options.toArray();
+              const options = this._options.toArray() as MatOption[];
```
Comment (macjohnny) [inline src/app/mat-select-search/mat-select-search.component.ts:340]: nit: this typecast should not be necessary, since  
https://github.com/angular/angular/blob/ee5b1cf076cb977b86bbe265e5243f145f4d1e4a/packages/core/src/linker/query_list.ts#L136  already has the correct return type, no?

**Review by macjohnny — APPROVED** [review]
Thank you very much for the fix and the corresponding test!

File: src/app/mat-select-search/mat-select-search.component.ts (hunk 2 above)
Comment (lorenzbaier) [reply src/app/mat-select-search/mat-select-search.component.ts]: yeah i removed it, i guess vscode didn't show it correctly the first time

**Review by macjohnny — APPROVED** [review]
