### PR TITLE
Fix setting firstActiveItem when data is appended

### LINKED ISSUE #200: Adding items to an existing list will cause MatSelect to scroll to first item.
I'm having a list of items and searching with server client.
I'm using a library to load more items once user reaches bottom of the scroll container. Problem is when I push new items to my list, it scrolls to first item.

The problem is not with the library I'm using, because even if I just randomly push an item to my list, it happens.

### PR DESCRIPTION
**Pull request by raysuelzer**
Proof of concept to resolve #200 
When the first item in the list hasn't actually changed, we can assume
that data has been added to the bottom of the list, so we don't need
to scroll back to the top of the list (via keymanager.setActiveItem).

I know there is probably a much nicer way to do this, but only had a little bit of time.
I tested this locally with the example from #205 and it solves that issue nicely, and all the other examples seem to work well.

https://stackblitz.com/edit/mat-select-search-with-infinity-scroll?file=src%2Fapp%2Fapp.module.ts

### CODE REVIEW

**Comment by raysuelzer** [comment]
So close, but won't work because we need to only fire this event after the options have changed once... Otherwise, the first time you scroll down it scrolls up to the top, and then after that it works fine. Will look tomorrow.

**Comment by raysuelzer** [comment]
There that should do it.

**Comment by raysuelzer** [comment]
Tests pass. looks like the failure is unrelated, can't find demo data in circleci?

File: src/app/mat-select-search/mat-select-search.component.ts [hunk 1]
```diff
@@ -284,17 +292,47 @@ export class MatSelectSearchComponent implements OnInit, OnDestroy, AfterViewIni
...
 
               // avoid "expression has been changed" error
               setTimeout(() => {
                 // set first item active and input width
-                keyManager.setFirstItemActive();
+
+                // The Options queryList will return the input text box
+                // as the first item, we don't consider that the 'first'
+                // item as it's not a selectable option for the user.
+                const currentFirstOption = options[1];
```
Comment (macjohnny) [inline src/app/mat-select-search/mat-select-search.component.ts:317]: this should depend on `this.matOption`, i.e.
```suggestion
                const currentFirstOption = options[this.matOption ? 1 : 0];
```

File: src/app/mat-select-search/mat-select-search.component.ts [hunk 2]
```diff
@@ -26,9 +26,10 @@ import {
 import { ViewportRuler } from '@angular/cdk/scrolling';
 import { LiveAnnouncer } from '@angular/cdk/a11y';
 import { Subject } from 'rxjs';
-import { delay, take, takeUntil } from 'rxjs/operators';
+import { delay, take, takeUntil, startWith } from 'rxjs/operators';
 
 import { MatSelectSearchClearDirective } from './mat-select-search-clear.directive';
+import { OptionGroupsExampleComponent } from '../examples/04-option-groups-example/option-groups-example.component';
```
Comment (macjohnny) [inline src/app/mat-select-search/mat-select-search.component.ts:32]:
```suggestion
```

**Comment by macjohnny** [comment]
thanks, will test and release it later today

**Comment by raysuelzer** [comment]
Looks like it was that bad import statement VSCode added for me :) good catch. 

on my other computer I added a really rough example for testing. I can push it into another branch at some point tomorrow, but I pretty much just copy and pasted the demo from #205 into a new folder. 

I'm sure there is a more elegant solution to this bug, but it's been around for about 6 months, so I suppose a working fix is better than no fix. Also didn't want to make it more complicated than necessary.

**Comment by raysuelzer** [comment]
Need anything else on my end to get this merged?

**Comment by macjohnny** [comment]
@raysuelzer I was trying to set up an example with infinity sorting, however, the problem persisted. Would you mind adding your example so it aso serves as a showcase?

**Comment by raysuelzer** [comment]
Will do now.

**Comment by raysuelzer** [comment]
I added an example, admittedly, it's not super transparent and it's mostly a copy paste job from the #205 example. 

I also fixed a typo on the `07-tooltip-select-all-example` folder

In the process I found & fixed a bug, I had introduce, which broke the ability to scroll the active item into view when the panel opened.

File: src/app/mat-select-search/mat-select-search.component.ts [hunk 3]
```diff
@@ -285,16 +285,51 @@ export class MatSelectSearchComponent implements OnInit, OnDestroy, AfterViewIni
...
+        // In order to avoid avoid causing the list to
+        // scroll to the top when options are added to the bottom of
+        // the list (eg: infinite scroll), we compare only
+        // the changes to the first options to determine if we
+        // should set the first item as active.
+        // This prevents unncessary scrolling to the top of the list
+        // when options are appended, but allows the first item
+        // in the list to be set as active by default when there
+        // is no active selection
+        let previousFirstOption = this._options.toArray()[this.matOption ? 1 : 0];
```
Comment (macjohnny) [inline src/app/mat-select-search/mat-select-search.component.ts:300]: how about storing a reference to `option.value` instead of `option`? because the `*ngFor` might recreate the existing options if the reference of the loop item changes when used without `trackBy`

**Comment by macjohnny** [comment]
@raysuelzer thanks for the example, I forgot to set the `disableScrollToActiveOnOptionsChanged` option

File: src/app/mat-select-search/mat-select-search.component.ts (hunk 3 above)
Comment (macjohnny) [reply src/app/mat-select-search/mat-select-search.component.ts:300]: I think it is fine like this, since a user can use the `trackBy` function, and distinction by value might not be the best implementation

**Comment by macjohnny** [comment]
will be released on monday

**Comment by raysuelzer** [comment]
I think the next thing to tackle, which might actually be hard / out of scope is #194
When dynamically loading data, if the option is removed at any point, mat-select assumes that no option is selected because it cannot match the value to an option.  This causes issues with the labels / placeholders etc.  This problem exists outside of this library, but clearly shows the limitations of trying to dynamically load options into mat-option-list or use virtual scrolling.
