### PR TITLE
fix selection of different instances of same object when using `multiple`

### LINKED ISSUE #215: [BUG] Restoring of old selection does not use `compareWith`
**Describe the bug**
In [mat-select-search.component.ts#L552](https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/src/app/mat-select-search/mat-select-search.component.ts#L552), the previously selected values are restored, if they have been removed by the new filter.
However, the used logic does not use the `compareWith`-function of the `mat-select` and so different instances of the same object cause problems.
In my case, if I search for a value I make a request to the server, resulting in new instances of the objects. If I deselect an already selected object, it won't be removed. Additionally, selected objects, which match the current search term, are added again, resulting in two instances being part of the value.

**To Reproduce**
Here is a [stackblitz based on ngx-mat-select-search-example](https://github-pjetju.stackblitz.io)

1. Open the select and select the first 2 banks (`Bank A (Switzerland)` and `Bank B (Switzerland)` ).
2. Search for `Switzerland`
3. Deselect `Bank A (Switzerland)`
4. In the `Selected Banks` `Bank A (Switzerland)` is still selected, `Bank B (Switzerland)` is selected twice.

**Expected behavior**
The `mat-select-search` should use the provided `compareWith`-Function to check if two objects are the same.

**Additional Information**
It should be enough to change [mat-select-search#L553](https://github.com/bithost-gmbh/ngx-mat-select-search/blob/master/src/app/mat-select-search/mat-select-search.component.ts#L553) from
```typescript
if (values.indexOf(previousValue) === -1 && optionValues.indexOf(previousValue) === -1)
```
to

```typescript
if (values.findIndex(v => this.matSelect.compareWith(v, previousValue)) === -1 && optionValues.findIndex(v => this.matSelect.compareWith(v, previousValue)) === -1)
```

### PR DESCRIPTION
**Pull request by Springrbua**
Fix #215

### CODE REVIEW

File: src/app/mat-select-search/mat-select-search.component.ts [hunk 1]
```diff
@@ -550,7 +550,8 @@ export class MatSelectSearchComponent implements OnInit, OnDestroy, AfterViewIni
             }
             const optionValues = this.matSelect.options.map(option => option.value);
             this.previousSelectedValues.forEach(previousValue => {
-              if (values.indexOf(previousValue) === -1 && optionValues.indexOf(previousValue) === -1) {
+              if (!values.find(v => this.matSelect.compareWith(v, previousValue))
```
Comment (macjohnny) [inline src/app/mat-select-search/mat-select-search.component.ts]:
```suggestion
              if (!values.some(v => this.matSelect.compareWith(v, previousValue))
```

File: src/app/mat-select-search/mat-select-search.component.ts [hunk 2]
```diff
@@ -550,7 +550,8 @@ export class MatSelectSearchComponent implements OnInit, OnDestroy, AfterViewIni
...
+                && !optionValues.find(v => this.matSelect.compareWith(v, previousValue))) {
```
Comment (macjohnny) [inline src/app/mat-select-search/mat-select-search.component.ts]:
```suggestion
                && !optionValues.some(v => this.matSelect.compareWith(v, previousValue))) {
```
