### PR TITLE
[FIX] Accessibility Issue: screenreaders reading blank before each option

### LINKED ISSUE #349: Accessibility Issue: Ngx-mat-select-search dropdown, navigating options in the dropdown using down arrow without search value, NVDA reading blank
Actual Behavior: While navigating options in the dropdown using down arrow without any search value, NVDA announcing "blank" and option in both speech viewer window and voice. 

For Example: if you take country list dropdown and navigate the options without search value then  NVDA announcing 

    blank
    Albania 1 of 15

Expected Behavior: While navigating options in the dropdown using down arrow, NVDA should announce the option from the list 

For Example: if you take country list dropdown and navigate the options without  search value then NVDA should announce 

    Albania 1 of 15

I tried using **disableInitialFocus** attribute to "**true**" then in dropdown options, user wont able to navigate and focus the search input through keyboard.

Any workaround for this issue ?

ngx-mat-select-search

### PR DESCRIPTION
**Pull request by escheiermann**
Fixes #349 

The problem was caused by the `selectSearchInput` keeping focus while browsing through the options with the arrow keys. Screenreaders would announce the current value of the input before each option.

When the ARIA properties `aria-activedescendant` and `aria-selected` are set properly on the input an mat-option elements, the screenreader will announce the option without reading the current input value.

To announce the correct number of options (e.g. '1 of 4'), the mat-option element conatining the ngx-mat-select-search must be applied with the `aria-hidden` property.

Therefore the `indexAndLengthScreenReaderText` property, the `getAriaIndex` and `getAriaLength` methods and the `LiveAnnouncer` are not necessary anymore.

### CODE REVIEW

File: src/app/mat-select-search/mat-select-search.component.ts [hunk 1]
```diff
@@ -499,40 +493,14 @@ export class MatSelectSearchComponent implements OnInit, OnDestroy, ControlValue
...
       if (index !== -1) {
-        const activeDescendant = this._options.toArray()[index];
-        this.liveAnnouncer.announce(
-          activeDescendant.viewValue + ' '
-          + this.getAriaIndex(index)
-          + this.indexAndLengthScreenReaderText
-          + this.getAriaLength()
-        );
+        this.activeDescendant?.removeAttribute('aria-selected');
+        this.activeDescendant = this._options.toArray()[index]._getHostElement();
```
Comment (macjohnny) [inline src/app/mat-select-search/mat-select-search.component.ts:497]: Please use a WeakRef here:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef

File: src/app/mat-select-search/mat-select-search.component.ts [hunk 2]
```diff
@@ -499,40 +493,14 @@ export class MatSelectSearchComponent implements OnInit, OnDestroy, ControlValue
...
+        this.activeDescendant.setAttribute('aria-selected', 'true');
```
Comment (macjohnny) [inline src/app/mat-select-search/mat-select-search.component.ts:498]: In theory, there could be events other than keydown/up that change the active descendant, so this and
The next line would be outdated. Did you investigate if this can happen?
Maybe there is an Observable for when the active descendant changes?

**Review by macjohnny — APPROVED** [review]
Thanks a lot for your contribution! This looks good.
After you applied the change with the WeakRef, this should be ready to be released

File: src/app/mat-select-search/mat-select-search.component.ts (hunk 1 above)
Comment (escheiermann) [reply src/app/mat-select-search/mat-select-search.component.ts]: I refactored the code to use a WeakRef, but apparently the CI build step `build-lib` is failing. To support the WeakRef, I had to upgrade the `lib` from es2017 to es2021. 

According to [Can I use](https://caniuse.com/mdn-javascript_builtins_weakref) the feature is not included in every browser version. I tried updating the `.browserslistrc` according to the table form Can I use, but the build would still fail. 

Personally, I haven't used the `ng-packagr` library before. Maybe you could help to get the build step working?

File: src/app/mat-select-search/mat-select-search.component.ts (hunk 2 above)
Comment (escheiermann) [reply src/app/mat-select-search/mat-select-search.component.ts]: The only situation I could figure out was that the set attributes become outdated after the component gets blurred. Therefore I introduced a `unselectActiveDescendant` method that gets called everytime the `blur` method gets called, so that the `aria-selected` and the `aria-activedescendant` attributes are removed properly.

File: src/app/mat-select-search/mat-select-search.component.ts (hunk 1 above)
Comment (escheiermann) [reply src/app/mat-select-search/mat-select-search.component.ts:497]: Since we only keep one reference per component this would propably not result in a lot of memory drain. So I think rolling back with the changes is okay in our situation.

I refactored the code again to use a solid reference like before. With that the build is now working and I would say the pull request is ready to be merged.
